#A Simple Python Program To Print A Poem...
print("")
print("Twinkle, twinkle, little star,")
print("How I wonder what you are!")
print("Up above the world so high,")
print("Like a diamond in the sky.")
print("")
print("When the blazing sun is gone,")
print("When he nothing shines upon,")
print("Then you show your little light,")
print("Twinkle, twinkle, all the night.")
print("")
print("Then the traveler in the dark")
print("Thanks you for your tiny spark,")
print("How could he see where to go,")
print("If you did not twinkle so?")
print("")
print("In the dark blue sky you keep,")
print("Often through my curtains peep,")
print("For you never shut your eye,")
print("Till the sun is in the sky...")